### ISSUE TITLE
babel config

### ISSUE THREAD

**Issue by MichalStangretNvm** [trzewiczek/js-stack-tutorail#11]
There is one crutial information missing about babel configuration that may be needed to compile code
transform-object-rest-spread has to be added to babel

`yarn add transform-object-rest-spread`
and then in .babelrc following has to be added:
```
    "plugins": [
      "transform-object-rest-spread"
    ]
```

**Comment by trzewiczek** [comment]
Thx for point out the issue. I'll add it to the tutorial soon. 

Just two things to point out though:  the installation name is different than the name used in `.babelrc` file, so it should go as:

```bash
yarn add --dev babel-plugin-transform-object-rest-spread
```

I would add it to `devDependencies` as well instead of production deps.
